version: '3.8'

services:
    app:
      build:
        context: .
      container_name: task-management-container
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_management
        - SPRING_DATASOURCE_USERNAME=sa
        - SPRING_DATASOURCE_PASSWORD=sa
      depends_on:
        - db

    db:
      image: postgres:latest
      container_name: postgres-container
      environment:
        POSTGRES_USER: sa
        POSTGRES_PASSWORD: sa
        POSTGRES_DB: task_management
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: