spring:
  application:
    name: task-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    # Disable Hibernate automatic schema generation because we are using Flyway
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true