CREATE table users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    login VARCHAR(50)                             NOT NULL,
    password VARCHAR(100)                            NOT NULL,
    role TEXT NOT NULL
)